### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by sbadia** [postmodern/ffi-bit_masks#3]
Hi here!

Version 0.1.0 of was released in 2013, we now have cool new features in the current master of ffi-bit_masks, what about a new release?

Thanks in advance!
- https://rubygems.org/gems/ffi-bit_masks

**Comment by postmodern** [comment]
Finally released 0.1.1 which contains the JRuby fix (58eef51444b9feb6dd70a7b613e04c5d47f9f686).

**Comment by sbadia** [comment]
thanks @postmodern :)
